version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - php

  - package-ecosystem: composer
    directory: /framework
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - framework

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - ci